application: rokumm
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /stats/.*
  script: stats.py
  login: admin
  auth_fail_action: redirect

- url: /.*
  script: mymedia.py
