application: rokumm
version: 1
runtime: python
api_version: 1
builtins:
- remote_api: on
- datastore_admin: on

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /static
  static_dir: static

- url: /.*
  script: mymedia.py

